import { z } from 'zod';

export const REMINDER_INTERVALS = ['1_MONTH', '2_WEEKS', '1_WEEK', '2_DAYS', '3_HOURS'] as const;

// Accepts any non-empty string ID.
// z.string().cuid() rejects IDs generated by some Prisma adapter versions.
const optionalId = z.string().min(1).optional();

export const DocumentQuerySchema = z.object({
  companyId: optionalId,
  serviceId: optionalId,
  category: z.string().max(50).optional(),
  fileType: z.enum(['PDF', 'DOC', 'DOCX', 'XLSX', 'CSV']).optional(),
  search: z.string().max(100).optional(),
  from: z.coerce.date().optional(),
  to: z.coerce.date().optional(),
  page: z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(100).default(20),
});

export const CreateDocumentSchema = z.object({
  title:            z.string().min(2).max(200).trim(),
  filename:         z.string().min(1).max(255),
  fileType:         z.enum(['PDF', 'DOC', 'DOCX', 'XLSX', 'CSV']),
  fileSize:         z.number().int().positive().max(50 * 1024 * 1024),
  category:         z.string().min(1).max(50).trim(),
  description:      z.string().max(500).optional(),
  companyId:        optionalId,
  serviceId:        optionalId,
  dateReceived:     z.coerce.date().optional(),
  expiryDate:       z.coerce.date().optional(),
  reminderSettings: z.array(z.enum(REMINDER_INTERVALS)).max(5).optional(),
});

export type DocumentQueryInput = z.infer<typeof DocumentQuerySchema>;
export type CreateDocumentInput = z.infer<typeof CreateDocumentSchema>;
